apiVersion: apps/v1
kind: Deployment
metadata:
  name: unicat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unicat
  template:
    metadata:
      labels:
        app: unicat
    spec:
      containers:
        - name: payment-service
          image: imreezan/payment-service
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: development
          ports:
            - containerPort: 3000
        - name: user-service
          image: imreezan/user-service
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: development
          ports:
            - containerPort: 4003
        - name: learner-service
          image: imreezan/learner-service
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: development
          ports:
            - containerPort: 8084
        - name: course-service
          image: imreezan/course-service
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: development
          ports:
            - containerPort: 4002
        - name: unicat-client
          image: imreezan/unicat-client
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
            # Add environment variables if needed
---
apiVersion: v1
kind: Service
metadata:
  name: unicat
spec:
  selector:
    app: unicat
  type: LoadBalancer
  ports:
    - name: payment-service
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: user-service
      protocol: TCP
      port: 4003
      targetPort: 4003
    - name: learner-service
      protocol: TCP
      port: 8084
      targetPort: 8084
    - name: course-service
      protocol: TCP
      port: 4002
      targetPort: 4002
    - name: unicat-client
      protocol: TCP
      port: 5173
      targetPort: 5173
